### PR TITLE
Added W5100S

### PR DESCRIPTION
**Pull request by taylor-an**
Create Draft pull request

### CODE REVIEW

**Comment by tj-An** [comment]
is it done?

**Comment by tj-An** [comment]
> 
> 
> Create Draft pull request

is it done?

**Comment by taylor-an** [comment]
> 
> 
> > Create Draft pull request
> 
> is it done?

It's done. I've checked once again.

**Comment by tj-An** [comment]
> 
> 
> > > Create Draft pull request
> > 
> > 
> > is it done?
> 
> It's done. I've checked once again.

Start review and pull request please.

**Comment by tj-An** [comment]
Thanks

> 
> 
> > > > Create Draft pull request
> > > 
> > > 
> > > is it done?
> > 
> > 
> > It's done. I've checked once again.
> 
> Start review and pull request please.

**Comment by tj-An** [comment]
I've checked once again.

**Comment by tj-An** [comment]
Merge pull request

**Pull request merged**
